replicaCount: 1

imagePullSecrets:
  - name: nexus-registry

image:
  repository: localhost:8082/gameverseacademy
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 6060
  nodePort: 30606

ingress:
  enabled: false

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

env: []

livenessProbe:
  tcpSocket:
    port: 6060
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 5

readinessProbe:
  tcpSocket:
    port: 6060
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5
